# Generated by Django 5.0.6 on 2024-06-15 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuz', '0002_alter_university_description_alter_university_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(default='slug-university', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='vuz.university'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='vuz.user'),
        ),
    ]
