# Generated by Django 5.0.6 on 2024-06-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuz', '0004_alter_feedback_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('moderator', 'Модератор'), ('applicant', 'Абитуриент')], max_length=255),
        ),
    ]
