# Generated by Django 5.0.6 on 2024-07-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuz', '0006_alter_feedback_body_alter_feedback_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='image',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
