# Generated by Django 5.0.6 on 2024-07-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuz', '0007_university_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='image',
            new_name='wikipage_url',
        ),
    ]
